default: &default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  primary: &primary_production
    <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  schema_search_path: budget,public