# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 'localhost'

test:
  <<: *default
  database: budget_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  schema_search_path: budget,public

  queue:
    url: <%= ENV['QUEUE_DATABASE_URL'] %>