# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 'localhost'

test:
  <<: *default
  database: budget_app_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    schema_search_path: budget,public
  cache:
    <<: *primary_production
    database: budget_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: budget_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: budget_app_production_cable
    migrations_paths: db/cable_migrate